códigos/clam/classification/urls.py
from django.conf.urls import url

from . import views

app_name = 'classification'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'review/$', views.review, name='review_tweets'),
    url(r'reviewed/$', views.all_reviewed, name='all-reviewed'),
    url(r'^export/csv/$', views.generate_csv, name='generate_csv'),
]

códigos/clam/mchelper/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('classification.urls'))
]

códigos/clam/classification/models.py
from django.db import models


class Tweet(models.Model):
    tweet_text = models.TextField(verbose_name='text', max_length=300)
    tweet_username = models.CharField(verbose_name='username', max_length=255)
    tweet_id = models.BigIntegerField(verbose_name='id do tweet')

    def __str__(self):
        return self.tweet_text


class Review(models.Model):
    review = (
        (1, 'Positivo'),
        (0, 'Neutro'),
        (-1, 'Negativo')
    )
    tweet = models.ForeignKey('Tweet', on_delete=models.CASCADE)
    ironic = models.BooleanField(verbose_name='contem ironia', default=False)
    review = models.IntegerField(verbose_name='Avaliacao', choices=review)

    def is_ironic(self):
        return self.ironic

    def __str__(self):
        return self.tweet.tweet_text

códigos/clam/classification/forms.py
import logging
from django import forms

logger = logging.getLogger("testlogger")


class ReviewForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.tweet = kwargs.pop('tweet', None)
        self.tweet_text = self.tweet.tweet_text
        super(ReviewForm, self).__init__(*args, **kwargs)

    review_choices = (
        (1, 'Positivo'),
        (0, 'Neutro'),
        (-1, 'Negativo')
    )
    review = forms.ChoiceField(choices=review_choices, required=True, label='Opinião do tweet',
                               widget=forms.RadioSelect())
    """
        TODO: when is non related, add option to remove field
    """
    ironic = forms.BooleanField(required=False, label='É irônico / não relacionado / não está em português?',
                                widget=forms.CheckboxInput(attrs={'class': 'checkbox-inline'}))
    tweet = forms.IntegerField(label='Tweet', widget=forms.HiddenInput())


class ReviewFormSet(forms.BaseFormSet):

    def __init__(self, *args, **kwargs):
        self.tweets = kwargs.pop('tweets', None)
        super(ReviewFormSet, self).__init__(*args, **kwargs)

    def _construct_form(self, i, **kwargs):
        return super(ReviewFormSet, self)._construct_form(
            i, tweet=self.tweets[i], **kwargs)

    def clean(self):
        if any(self.errors):
            return


class CSVUploadForm(forms.Form):
    csv_file = forms.FileField(label='Arquivo csv (atenção, os elementos devem ser separados por virgula)')

códigos/clam/classification/views.py
import csv
import logging
import random
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.forms import formset_factory
from .models import Tweet, Review
from .forms import ReviewForm, ReviewFormSet, CSVUploadForm


def index(request):
    return render(request, 'classification/index.html', None)


def get_n_random(n):
    items = []
    tweets = Tweet.objects.filter(review__isnull=True)
    for i in range(n):
        items.append(random.choice(tweets))
    return items


def review(request):

    formset = formset_factory(ReviewForm, formset=ReviewFormSet, extra=0)
    logger = logging.getLogger('testlogger')

    if request.method == 'POST':
        """
            TODO: fazer query menor para quando for POST, depende do int do else
        """

        tweets = Tweet.objects.filter(review__isnull=True)
        review_formset = formset(request.POST, tweets=tweets)

        if review_formset.is_valid():
            logger.info('vou começar a registrar as opinioes')

            for review_form in review_formset:
                tweet_id = review_form.cleaned_data.get('tweet')
                review = review_form.cleaned_data.get('review')
                ironic = review_form.cleaned_data.get('ironic')
                reviewed_tweet = Tweet.objects.get(pk=tweet_id)
                user_review = Review(
                    tweet=reviewed_tweet,
                    review=review,
                    ironic=ironic
                )
                user_review.save()

            logger.info('terminei de colocar as opinioes')
            return redirect('classification:all-reviewed')

        else:
            context = {'review_formset': review_formset}
            return render(request, 'classification/review.html', context)

    else:
        tweets_amount = int(request.GET['tweets_amount'])
        tweets_to_review = get_n_random(tweets_amount)
        review_formset = formset(initial=[{'tweet': tweet.pk} for tweet in tweets_to_review],
                                 tweets=tweets_to_review)
        context = {'review_formset': review_formset, 'amount': tweets_amount}
        return render(request, 'classification/review.html', context)


def all_reviewed(request):
    reviewed_tweets = Tweet.objects.filter(review__isnull=False)
    context = {'reviewed_tweets': reviewed_tweets}
    return render(request, 'classification/show_reviewed.html', context)


def generate_csv(request):
    """
        TODO: refatorar esse metodo para tirar o if do for, fazer isso antes de deployar pra valer
    """
    logger = logging.getLogger('testlogger')
    logger.info("gerando csv")
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="tweets_classificados.csv"'
    writer = csv.writer(response)
    writer.writerow(['username', 'tweet', 'review'])
    reviewed_tweets = Tweet.objects.filter(review__isnull=False) \
        .filter(review__ironic=False)

    for tweet in reviewed_tweets:
        logger.info("texto: {}".format(tweet.tweet_text.encode('utf-8').decode('utf-8')))
        writer.writerow(
            [tweet.tweet_username, tweet.tweet_text.encode('utf-8').decode('utf-8'), tweet.review_set.all()[0].review])

    logger.info("csv gerado!")
    return response

códigos/clam/classification/templates/classification/index.html
{% extends "base.html" %}

{% block title %}Classificação de Tweets{% endblock %}

{% block content %}
<form method='GET' action='review/'>
    <div class="row">
        <div class="form-group col-md-6">
            <label for="tweets-to-be-reviewed">Quantos tweets você deseja classificar?</label>
            <input type="number" class="form-control" value="10" id="tweets_amount" name="tweets_amount" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <button type="submit" class="btn btn-default">Enviar</button>
        </div>
    </div>
</form>
{% endblock %}

códigos/clam/classification/templates/classification/review.html
{% extends "base.html" %}

{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}
{% load material_form %}

{% block title %}Classificar tweets {% endblock %}

{% block content %}
    <h1> Tweets para classificar </h1>
    <h5> Classifique se o texto do tweet apresenta uma opinião positiva ou negativa em relação ao candidato à Presidência da República relacionado.</h5>
    <form method='POST'>
        {% csrf_token %}
        {% for review_form in review_formset %}
            {% form form=review_form %}{% endform %}
        {% endfor %}
        <button type="submit" name="_submit" class="btn">Submit</button>
    </form>
{% endblock %}

códigos/clam/classification/templates/classification/show_reviewed.html
{% extends "base.html" %}

{% block title %}
    Tweets já classificados
{% endblock %}

{% block content %}
<a href="{% url 'classification:generate_csv' %}">Exportar CSV com os tweets já classificados</a>

<table class="table">
    <thead>
        <th>Username</th>
        <th>Texto</th>
        <th>Opinião</th>
    </thead>
    <tbody>
        {% for tweet in reviewed_tweets %}
            <tr>
                <td>
                    {{ tweet.tweet_username }}
                </td>
                <td>
                    {{ tweet.tweet_text }}
                </td>
                <td>
                    {{ tweet.review_set.all.0.get_review_display }}
                </td>
            </tr>
        {% endfor %}
        <tr>
        </tr>
    </tbody>
</table>
{% endblock %}

códigos/clam/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        {% load static %} 
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
        <link rel="stylesheet" href="{% static "css/custom.css" %}" />
        <title>{% block title %}Meu titulo TOP {% endblock %} </title>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">    
                        <img class="header-icon" src="{% static "images/big-clam.svg" %}" alt="logo" />
                    </a>
                    <p class="navbar-text">
                        Classificador Manual de Tweets (Clam)
                    </p>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'classification:index' %}">Classificar Tweets</a></li>
                        <li><a href="{% url 'classification:all-reviewed' %}">Tweets Classificados</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>
        <main class="content">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </main>
        <footer class="footer">
            <div class="container footer-content">
                Desenvolvido por Lucas Romão Silva. Alterações por Lucas Helfstein. <br />
                Código fonte: <a href="https://github.com/romaolucas/manual-classifier-helper"> https://github.com/romaolucas/manual-classifier-helper</a>

                <div>
                    Ícone feito por 
                    <a href="http://www.freepik.com" title="Freepik">Freepik</a> de <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> licenciado por <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
                </div>
            </div>
        </footer>
    </body>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>